### ISSUE TITLE
config.yaml.example配置文件中修改wechat的值

### ISSUE THREAD

**Issue by auyeungcarl** [houko/wechatgpt#16]
config.yaml.example配置文件中应该修改true，带上双引号；否则读取配置项不能识别。
```yaml
chatgpt:
  token: your chatgpt apiKey
  wechat: "true"
  wechat_keyword: chatgpt
  #telegram: your telegram token
  #tgWhitelist: username1,username2
  #tgKeyword: chatgpt

```
